# Generated by Django 2.0.3 on 2018-03-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_number', models.IntegerField()),
                ('unit_id', models.CharField(max_length=10)),
                ('incident_number', models.IntegerField()),
                ('call_type', models.TextField()),
                ('call_date', models.DateField()),
                ('watch_date', models.DateField()),
                ('received_timestamp', models.DateTimeField()),
                ('entry_timestamp', models.DateTimeField()),
                ('dispatch_timestamp', models.DateTimeField()),
                ('response_timestamp', models.DateTimeField()),
                ('on_scene_timestamp', models.DateTimeField()),
                ('transport_timestamp', models.DateTimeField()),
                ('hospital_timestamp', models.DateTimeField()),
                ('call_final_disposition', models.TextField()),
                ('available_timestamp', models.DateTimeField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('zipcode_of_incident', models.CharField(max_length=5)),
                ('battalion', models.CharField(max_length=3)),
                ('station_area', models.CharField(max_length=2)),
                ('box', models.CharField(max_length=4)),
                ('original_priority', models.CharField(max_length=1)),
                ('priority', models.CharField(max_length=1)),
                ('final_priority', models.IntegerField()),
                ('als_unit', models.BooleanField()),
                ('call_type_group', models.TextField()),
                ('number_of_alarms', models.IntegerField()),
                ('unit_type', models.TextField()),
                ('unit_sequence_in_call_dispatch', models.IntegerField()),
                ('fire_prevention_district', models.CharField(max_length=2)),
                ('supervisor_district', models.CharField(max_length=2)),
                ('neighborhood_district', models.CharField(max_length=2, null=True)),
                ('row_id', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=13)),
            ],
        ),
    ]
