# Generated by Django 2.0.3 on 2018-03-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='location',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
