# Generated by Django 2.0.3 on 2018-03-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_call_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='hospital_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='transport_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
