# Generated by Django 2.0.3 on 2018-03-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_auto_20180310_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='hospital_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='transport_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
