# Generated by Django 2.0.3 on 2018-03-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_auto_20180310_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='on_scene_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
