# Generated by Django 2.0.3 on 2018-03-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0006_auto_20180310_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
