# Generated by Django 2.0.3 on 2018-03-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0007_auto_20180310_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='fire_prevention_district',
            field=models.CharField(max_length=4),
        ),
    ]
