# Generated by Django 2.0.3 on 2018-03-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0008_auto_20180310_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='call_type_group',
            field=models.TextField(blank=True, null=True),
        ),
    ]
