# Generated by Django 2.0.3 on 2018-03-11 22:57

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0009_auto_20180310_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
